name: build and test

on: [push]

jobs:
  build:
 
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout...
      uses: actions/checkout@v1
    - name: setup JDK...
      uses: actions/setup-java@v1
      with:
        java-version: 9
    - name: lscpu
      run: lscpu;df -h
    - name: prepare...
      run: ./00-prep.sh m2 /opt/hostedtoolcache/Java/9.0.7/x64 token true SNAPHOT
    - name: get tools
      run: ./01-getTools.sh
    - name: make poms
      run: ./02-makePoms.sh
    - name: get dependencies
      run: ./03-getDependencies.sh
    - name: build
      run: ./04-build.sh
    - name: test
      run: ./05-test.sh
    - name: generate javadoc
      run: ./06-javadoc.sh
    - name: publish
      run: ./07-publish.sh
