name: build and test

on: [push]

jobs:
  build-and-test:
 
    runs-on: ubuntu-latest
    
    steps:
    #- name: machine features
    #  run:  sudo apt-get install htop aha; lscpu; df -h; export TERM=linux; echo tHq | htop 2>&1 >/dev/null; echo q | COLUMNS=300 ROWS=300 htop | aha --black --line-fix

    - name: checkout...
      uses: actions/checkout@v1
    - name: setup JDK...
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: prepare...
      run:  build/00-prep.sh ${{ secrets.GITHUB_TOKEN }}
    - name: get tools
      run:  build/01-getTools.sh
    - name: make poms
      run:  build/02-makePoms.sh

#========================================================================================================
    - name: cache m2
      uses: actions/cache@v1
      with:
        path: m2
        key: m2-${{ hashFiles('out/artifacts/ALL-SNAPSHOT.pom') }}
#========================================================================================================

    - name: get dependencies
      run:  build/03-getDependencies.sh
    - name: build
      run:  build/04-build.sh

#========================================================================================================
    - name: archive collections
      uses: actions/upload-artifact@v1
      with:
        name: collections.jar
        path: out/artifacts/collections-SNAPSHOT.jar
    - name: archive transactions
      uses: actions/upload-artifact@v1
      with:
        name: transactions.jar
        path: out/artifacts/transactions-SNAPSHOT.jar
    - name: archive jdclare
      uses: actions/upload-artifact@v1
      with:
        name: jdclare.jar
        path: out/artifacts/jdclare-SNAPSHOT.jar
#========================================================================================================

    - name: test
      run:  build/05-test.sh

#========================================================================================================
    - name: cache javadoc collections
      uses: actions/cache@v1
      with:
        path: cache/collections
        key: javadoc-${{ hashFiles('org.modelingvalue.collections/src/**/*.java') }}
    - name: cache javadoc transactions
      uses: actions/cache@v1
      with:
        path: cache/transactions
        key: javadoc-${{ hashFiles('org.modelingvalue.transactions/src/**/*.java') }}
    - name: cache javadoc jdclare
      uses: actions/cache@v1
      with:
        path: cache/jdclare
        key: javadoc-${{ hashFiles('org.modelingvalue.jdclare/src/**/*.java') }}
#========================================================================================================

    - name: generate javadoc
      run:  build/06-javadoc.sh

    - name: publish
      run:  build/07-publish.sh
