name: Java CI

on: [push]

jobs:
  build:
 
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 9
    - name: Build with Ant
      run: ant -noinput -Djdk.home.9.0=$JDK_HOME -buildfile build.xml
