name: Java CI

on: [push]

jobs:
  build:
 
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup...
      uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 9
    - name: build
      run: >
        ./build.sh
        ./m2
        /opt/hostedtoolcache/Java/9.0.7/x64
        token
        true
        SNAPHOT
